---

- hosts: all
  roles:
    - franklinkim.users-oh-my-zsh
  vars:
    users:
      - name: Foo Bar
        username: foobar
        authorized_keys: []
        oh_my_zsh:
          theme: supertheme
