---

- include: install.yml
  tags:
    - system
    - users-oh-my-zsh
    - install
    - install-users-oh-my-zsh

- include: config.yml
  tags:
    - system
    - users-oh-my-zsh
    - config
    - config-users-oh-my-zsh
